name: '🐛Bug'
description: '버그 이슈를 생성합니다. 버그 및 오류 이슈 템플릿입니다.'
labels: bug
title: '[Bug]'
body:

  - type: textarea
    id: description
    attributes:
      label: '📝 상세 내용(Description)'
      description: '발생한 버그 및 오류에 대해서 설명해주세요'
    validations:
      required: true

  - type: textarea
    id: tasks
    attributes:
      label: '✅ Todo'
      description: '해당 버그 및 오류 해결을 위해 해야할 작업목록을 작성해주세요'
      value: |
        - [ ] Task1
        - [ ] Task2
    validations:
      required: true