name: '✨Feature'
description: 'Feature 이슈를 생성합니다. 기능 추가 이슈 템플릿입니다.'
labels: feat
title: '[Feature]'
body:

  - type: textarea
    id: description
    attributes:
      label: '📝 상세 내용(Description)'
      description: '구현할 기능에 대해서 설명해주세요'
    validations:
      required: true

  - type: textarea
    id: tasks
    attributes:
      label: '✅ Todo'
      description: '해당 기능에 대해 해야할 작업목록을 작성해주세요'
      value: |
        - [ ] Task1
        - [ ] Task2
    validations:
      required: true