name: '♻️Refactor'
description: '리팩토링 이슈를 생성합니다. 코드 리팩토링 이슈 템플릿입니다.'
labels: refactor
title: '[Refactor]'
body:

  - type: textarea
    id: description
    attributes:
      label: '📝 상세 내용(Description)'
      description: '리팩토링 할 내용에 대해서 설명해주세요'
    validations:
      required: true

  - type: textarea
    id: tasks
    attributes:
      label: '✅ Todo'
      description: '코드 리팩토링을 위해 해야할 작업목록을 작성해주세요'
      value: |
        - [ ] Task1
        - [ ] Task2
    validations:
      required: true